name: publish-docker

on:
  push:
    branches:
      - main

env:
  HUB: ghcr.io/arugal/docker-demo

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 90
    env:
      TAG: ${{ github.sha }}
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.HUB }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker images
        run: docker build -t ${HUB}:${TAG} . && docker push ${HUB}:${TAG}